theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - 1-Register/README.md
  - 2-Setup/README.md
  - 3-ForgeViewerBoiler/README.md
  - 4-OAuth-SDK/README.md
  - 5-Bucket-Management/README.md
  - 6-Model-Translation/README.md
  - 7-View-Model/README.md